
#pragma once

enum
{
    PID_NONE         = 0x00,

    // Player Characters
    PID_EIRIKA       = 0x01,
    PID_SETH         = 0x02,
    PID_GILLIAM      = 0x03,
    PID_FRANZ        = 0x04,
    PID_MOULDER      = 0x05,
    PID_VANESSA      = 0x06,
    PID_ROSS         = 0x07,
    PID_NEIMI        = 0x08,
    PID_COLM         = 0x09,
    PID_GARCIA       = 0x0A,
    PID_INNES        = 0x0B,
    PID_LUTE         = 0x0C,
    PID_NATASHA      = 0x0D,
    PID_CORMAG       = 0x0E,
    PID_EPHRAIM      = 0x0F,
    PID_FORDE        = 0x10,
    PID_KYLE         = 0x11,
    PID_AMELIA       = 0x12,
    PID_ARTUR        = 0x13,
    PID_GERIK        = 0x14,
    PID_TETHYS       = 0x15,
    PID_MARISA       = 0x16,
    PID_SALEH        = 0x17,
    PID_EWAN         = 0x18,
    PID_LARACHEL     = 0x19,
    PID_DOZLA        = 0x1A,
    PID_RENNAC       = 0x1C,
    PID_DUESSEL      = 0x1D,
    PID_MYRRH        = 0x1E,
    PID_KNOLL        = 0x1F,
    PID_JOSHUA       = 0x20,
    PID_SYRENE       = 0x21,
    PID_TANA         = 0x22,
    PID_LYON_CC      = 0x23,
    PID_ORSON_CC     = 0x24,
    PID_GLEN_CC      = 0x25,
    PID_SELENA_CC    = 0x26,
    PID_VALTER_CC    = 0x27,
    PID_RIEV_CC      = 0x28,
    PID_CAELLACH_CC  = 0x29,
    PID_FADO_CC      = 0x2A,
    PID_ISMAIRE_CC   = 0x2B,
    PID_HAYDEN_CC    = 0x2C,

    // Summoned Characters
    PID_SUMMON_LYON  = 0x3B,
    PID_SUMMON_KNOLL = 0x3E,
    PID_SUMMON_EWAN  = 0x3F,

    // Boss/Unique Enemy Characters
    PID_LYON         = 0x40,
    PID_MORVA        = 0x41,
    PID_ORSON_CH5X   = 0x42,
    PID_VALER        = 0x43,
    PID_SELENA       = 0x44,
    PID_VALTER_PROLOGUE = 0x45,
    PID_BREGUET      = 0x46,
    PID_BONE         = 0x47,
    PID_BAZBA        = 0x48,
    PID_ENTOUMBED_CH4 = 0x49,
    PID_SAAR         = 0x4A,
    PID_NOVALA       = 0x4B,
    PID_MURRAY       = 0x4C,
    PID_TIRADO       = 0x4D,
    PID_BINKS        = 0x4E,
    PID_PABLO        = 0x4F,
    PID_MAELDUIN_CHUnk = 0x50, // TODO: which chapter?
    PID_AIAS         = 0x51,
    PID_CARLYLE      = 0x52,
    PID_CAELLACH     = 0x53,
    PID_PABLO_2      = 0x54, // TODO: which chapter?
    PID_GORGON_CHUnk = 0x56, // TODO: which chapter?
    PID_RIEV         = 0x57,
    PID_GHEB         = 0x5A,
    PID_BERAN        = 0x5B,
    PID_CYCLOPS_CHUnk = 0x5C,
    PID_WIGHT_CHUnk  = 0x5D,
    PID_DEATHGOYLE_CHUnk = 0x5E,
    PID_BANDIT_CH5   = 0x66,
    PID_ONEILL       = 0x68,
    PID_GLEN         = 0x69,
    PID_ZONTA        = 0x6A,
    PID_VIGARDE      = 0x6B,
    PID_LYON_FINAL   = 0x6C,
    PID_ORSON        = 0x6D,

    PID_FOMORTIIS    = 0xBE,

    PID_WALL         = 0xFE,
    PID_SNAG         = 0xFF,
};
